/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.cedar.schemas.avro.geojson;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum MultiPointType {
  MultiPoint  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MultiPointType\",\"namespace\":\"org.cedar.psi.common.avro\",\"symbols\":[\"MultiPoint\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
