/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.cedar.schemas.avro.geojson;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PolygonType {
  Polygon  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PolygonType\",\"namespace\":\"org.cedar.psi.common.avro\",\"symbols\":[\"Polygon\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
