/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.cedar.schemas.avro.psi;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** TBD */
@org.apache.avro.specific.AvroGenerated
public class Identifiers extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7974374939382609379L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Identifiers\",\"namespace\":\"org.cedar.psi.common.avro\",\"doc\":\"TBD\",\"fields\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Creates a new Identifiers RecordBuilder.
   * @return A new Identifiers RecordBuilder
   */
  public static Identifiers.Builder newBuilder() {
    return new Identifiers.Builder();
  }

  /**
   * Creates a new Identifiers RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Identifiers RecordBuilder
   */
  public static Identifiers.Builder newBuilder(Identifiers.Builder other) {
    return new Identifiers.Builder(other);
  }

  /**
   * Creates a new Identifiers RecordBuilder by copying an existing Identifiers instance.
   * @param other The existing instance to copy.
   * @return A new Identifiers RecordBuilder
   */
  public static Identifiers.Builder newBuilder(Identifiers other) {
    return new Identifiers.Builder(other);
  }

  /**
   * RecordBuilder for Identifiers instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Identifiers>
    implements org.apache.avro.data.RecordBuilder<Identifiers> {


    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Identifiers.Builder other) {
      super(other);
    }

    /**
     * Creates a Builder by copying an existing Identifiers instance
     * @param other The existing instance to copy.
     */
    private Builder(Identifiers other) {
            super(SCHEMA$);
    }

    @Override
    public Identifiers build() {
      try {
        Identifiers record = new Identifiers();
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
