/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.cedar.schemas.avro.psi;
@SuppressWarnings("all")
/** An HTTP request method */
@org.apache.avro.specific.AvroGenerated
public enum Method {
  HEAD, OPTIONS, GET, POST, PUT, PATCH, DELETE, TRACE, CONNECT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Method\",\"namespace\":\"org.cedar.psi.common.avro\",\"doc\":\"An HTTP request method\",\"symbols\":[\"HEAD\",\"OPTIONS\",\"GET\",\"POST\",\"PUT\",\"PATCH\",\"DELETE\",\"TRACE\",\"CONNECT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
