/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.cedar.schemas.avro.psi;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SpatialBoundingAnalysis extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4939071363179654923L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SpatialBoundingAnalysis\",\"namespace\":\"org.cedar.psi.common.avro\",\"fields\":[{\"name\":\"spatialBoundingExists\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private boolean spatialBoundingExists;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SpatialBoundingAnalysis() {}

  /**
   * All-args constructor.
   * @param spatialBoundingExists The new value for spatialBoundingExists
   */
  public SpatialBoundingAnalysis(Boolean spatialBoundingExists) {
    this.spatialBoundingExists = spatialBoundingExists;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return spatialBoundingExists;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: spatialBoundingExists = (Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'spatialBoundingExists' field.
   * @return The value of the 'spatialBoundingExists' field.
   */
  public Boolean getSpatialBoundingExists() {
    return spatialBoundingExists;
  }


  /**
   * Creates a new SpatialBoundingAnalysis RecordBuilder.
   * @return A new SpatialBoundingAnalysis RecordBuilder
   */
  public static SpatialBoundingAnalysis.Builder newBuilder() {
    return new SpatialBoundingAnalysis.Builder();
  }

  /**
   * Creates a new SpatialBoundingAnalysis RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SpatialBoundingAnalysis RecordBuilder
   */
  public static SpatialBoundingAnalysis.Builder newBuilder(SpatialBoundingAnalysis.Builder other) {
    return new SpatialBoundingAnalysis.Builder(other);
  }

  /**
   * Creates a new SpatialBoundingAnalysis RecordBuilder by copying an existing SpatialBoundingAnalysis instance.
   * @param other The existing instance to copy.
   * @return A new SpatialBoundingAnalysis RecordBuilder
   */
  public static SpatialBoundingAnalysis.Builder newBuilder(SpatialBoundingAnalysis other) {
    return new SpatialBoundingAnalysis.Builder(other);
  }

  /**
   * RecordBuilder for SpatialBoundingAnalysis instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SpatialBoundingAnalysis>
    implements org.apache.avro.data.RecordBuilder<SpatialBoundingAnalysis> {

    private boolean spatialBoundingExists;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(SpatialBoundingAnalysis.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.spatialBoundingExists)) {
        this.spatialBoundingExists = data().deepCopy(fields()[0].schema(), other.spatialBoundingExists);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SpatialBoundingAnalysis instance
     * @param other The existing instance to copy.
     */
    private Builder(SpatialBoundingAnalysis other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.spatialBoundingExists)) {
        this.spatialBoundingExists = data().deepCopy(fields()[0].schema(), other.spatialBoundingExists);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'spatialBoundingExists' field.
      * @return The value.
      */
    public Boolean getSpatialBoundingExists() {
      return spatialBoundingExists;
    }

    /**
      * Sets the value of the 'spatialBoundingExists' field.
      * @param value The value of 'spatialBoundingExists'.
      * @return This builder.
      */
    public SpatialBoundingAnalysis.Builder setSpatialBoundingExists(boolean value) {
      validate(fields()[0], value);
      this.spatialBoundingExists = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'spatialBoundingExists' field has been set.
      * @return True if the 'spatialBoundingExists' field has been set, false otherwise.
      */
    public boolean hasSpatialBoundingExists() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'spatialBoundingExists' field.
      * @return This builder.
      */
    public SpatialBoundingAnalysis.Builder clearSpatialBoundingExists() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public SpatialBoundingAnalysis build() {
      try {
        SpatialBoundingAnalysis record = new SpatialBoundingAnalysis();
        record.spatialBoundingExists = fieldSetFlags()[0] ? this.spatialBoundingExists : (Boolean) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
