/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.cedar.schemas.avro.psi;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ThumbnailAnalysis extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2289369686678099108L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ThumbnailAnalysis\",\"namespace\":\"org.cedar.psi.common.avro\",\"fields\":[{\"name\":\"thumbnailExists\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private boolean thumbnailExists;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ThumbnailAnalysis() {}

  /**
   * All-args constructor.
   * @param thumbnailExists The new value for thumbnailExists
   */
  public ThumbnailAnalysis(Boolean thumbnailExists) {
    this.thumbnailExists = thumbnailExists;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return thumbnailExists;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: thumbnailExists = (Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'thumbnailExists' field.
   * @return The value of the 'thumbnailExists' field.
   */
  public Boolean getThumbnailExists() {
    return thumbnailExists;
  }


  /**
   * Creates a new ThumbnailAnalysis RecordBuilder.
   * @return A new ThumbnailAnalysis RecordBuilder
   */
  public static ThumbnailAnalysis.Builder newBuilder() {
    return new ThumbnailAnalysis.Builder();
  }

  /**
   * Creates a new ThumbnailAnalysis RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ThumbnailAnalysis RecordBuilder
   */
  public static ThumbnailAnalysis.Builder newBuilder(ThumbnailAnalysis.Builder other) {
    return new ThumbnailAnalysis.Builder(other);
  }

  /**
   * Creates a new ThumbnailAnalysis RecordBuilder by copying an existing ThumbnailAnalysis instance.
   * @param other The existing instance to copy.
   * @return A new ThumbnailAnalysis RecordBuilder
   */
  public static ThumbnailAnalysis.Builder newBuilder(ThumbnailAnalysis other) {
    return new ThumbnailAnalysis.Builder(other);
  }

  /**
   * RecordBuilder for ThumbnailAnalysis instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ThumbnailAnalysis>
    implements org.apache.avro.data.RecordBuilder<ThumbnailAnalysis> {

    private boolean thumbnailExists;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ThumbnailAnalysis.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.thumbnailExists)) {
        this.thumbnailExists = data().deepCopy(fields()[0].schema(), other.thumbnailExists);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ThumbnailAnalysis instance
     * @param other The existing instance to copy.
     */
    private Builder(ThumbnailAnalysis other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.thumbnailExists)) {
        this.thumbnailExists = data().deepCopy(fields()[0].schema(), other.thumbnailExists);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'thumbnailExists' field.
      * @return The value.
      */
    public Boolean getThumbnailExists() {
      return thumbnailExists;
    }

    /**
      * Sets the value of the 'thumbnailExists' field.
      * @param value The value of 'thumbnailExists'.
      * @return This builder.
      */
    public ThumbnailAnalysis.Builder setThumbnailExists(boolean value) {
      validate(fields()[0], value);
      this.thumbnailExists = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'thumbnailExists' field has been set.
      * @return True if the 'thumbnailExists' field has been set, false otherwise.
      */
    public boolean hasThumbnailExists() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'thumbnailExists' field.
      * @return This builder.
      */
    public ThumbnailAnalysis.Builder clearThumbnailExists() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public ThumbnailAnalysis build() {
      try {
        ThumbnailAnalysis record = new ThumbnailAnalysis();
        record.thumbnailExists = fieldSetFlags()[0] ? this.thumbnailExists : (Boolean) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
